export const IPC_EVENTS = {
  // facebook
  FB_OPEN_LOGIN: "FB_OPEN_LOGIN",
  FB_CHECK_SESSION: "FB_CHECK_SESSION",
  FB_LOG_OUT: "FB_LOG_OUT",
  FB_SCRAPE_MARKET_LISTINGS: "FB_SCRAPE_MARKET_LISTINGS",
  FB_ON_SCRAPE_PROGRESS: "FB_ON_SCRAPE_PROGRESS",
  FB_OPEN_BROWSER: "FB_OPEN_BROWSER",

  // llm
  LLM_ANALYZE_LISTINGS: "LLM_ANALYZE_LISTINGS",

  // listingRepo
  LISTING_GET_SAVED: "LISTING_GET_SAVED",
  LISTING_GET_PENDING: "LISTING_GET_PENDING",
  LISTING_GET_DISCARDED: "LISTING_GET_DISCARDED",
  LISTING_SAVE: "LISTING_SAVE",
  LISTING_CHANGE_STATUS: "LISTING_CHANGE_STATUS",
  LISTING_DELETE: "LISTING_DELETE",
  LISTING_DELETE_ALL_BY_STATUS: "LISTING_DELETE_ALL_BY_STATUS",

  // settingsRepo
  SETTINGS_GET_API_KEY: "SETTINGS_GET_API_KEY",
  SETTINGS_SET_API_KEY: "SETTINGS_SET_API_KEY",
  SETTINGS_GET_LOCATION: "SETTINGS_GET_LOCATION",
  SETTINGS_SET_LOCATION: "SETTINGS_SET_LOCATION"
} as const;

export type IpcEvent = (typeof IPC_EVENTS)[keyof typeof IPC_EVENTS];
